# Arrays con NumPy

In [ ]:
# Primero debemos importar la libreria

In [2]:
import numpy as np

In [4]:
# Inicializar un array en numpy usando una lista como arg
indicadores = np.array([3.4, 5.6, 7.8, 1.2, 9.9])

In [5]:
type(indicadores)

numpy.ndarray

In [6]:
indicadores

array([3.4, 5.6, 7.8, 1.2, 9.9])

In [9]:
# dimension de un array
indicadores.shape

(5,)

In [10]:
# Crear arrays en 2D
matrizA = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]) # Matriz cuadrada

In [11]:
matrizA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
type(matrizA)

numpy.ndarray

In [13]:
# para saber la dimension de un array
matrizA.shape

(3, 3)

In [15]:
matrizB = np.array([[1,2], [3,4], [5, 6]])

In [16]:
matrizB

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
matrizB.shape

(3, 2)

## Operaciones sobre ndarray

In [34]:
# Funcion 'arange' de numpy
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
numeros = np.arange(3, 15)

In [22]:
numeros

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
type(numeros)

numpy.ndarray

In [24]:
# Operaciones
numeros * 2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [25]:
numeros ** 3

array([  27,   64,  125,  216,  343,  512,  729, 1000, 1331, 1728, 2197,
       2744])

In [27]:
numeros

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
numeros += 1

In [30]:
numeros

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [31]:
numeros

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [32]:
numeros -= 1

In [33]:
numeros

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
# Funcion linspace

In [36]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 

In [37]:
np.linspace(1.5, 7.5, 5)

array([1.5, 3. , 4.5, 6. , 7.5])

In [39]:
np.linspace(0, 1, 300) # Se genera 300 numeros entre 0 y 1 incluidos el 0 y el 1

array([0.        , 0.00334448, 0.00668896, 0.01003344, 0.01337793,
       0.01672241, 0.02006689, 0.02341137, 0.02675585, 0.03010033,
       0.03344482, 0.0367893 , 0.04013378, 0.04347826, 0.04682274,
       0.05016722, 0.05351171, 0.05685619, 0.06020067, 0.06354515,
       0.06688963, 0.07023411, 0.0735786 , 0.07692308, 0.08026756,
       0.08361204, 0.08695652, 0.090301  , 0.09364548, 0.09698997,
       0.10033445, 0.10367893, 0.10702341, 0.11036789, 0.11371237,
       0.11705686, 0.12040134, 0.12374582, 0.1270903 , 0.13043478,
       0.13377926, 0.13712375, 0.14046823, 0.14381271, 0.14715719,
       0.15050167, 0.15384615, 0.15719064, 0.16053512, 0.1638796 ,
       0.16722408, 0.17056856, 0.17391304, 0.17725753, 0.18060201,
       0.18394649, 0.18729097, 0.19063545, 0.19397993, 0.19732441,
       0.2006689 , 0.20401338, 0.20735786, 0.21070234, 0.21404682,
       0.2173913 , 0.22073579, 0.22408027, 0.22742475, 0.23076923,
       0.23411371, 0.23745819, 0.24080268, 0.24414716, 0.24749

In [40]:
numeros

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
len(numeros)

12

In [42]:
numeros2 = np.linspace(1, 5, 10)

In [43]:
numeros2

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [44]:
# Operaciones entre arrays
numeros * numeros2

ValueError: operands could not be broadcast together with shapes (12,) (10,) 

In [45]:
numeros2 = np.linspace(1, 5, 12)

In [46]:
numeros2

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [47]:
numeros * numeros2

array([ 4.        ,  6.81818182, 10.36363636, 14.63636364, 19.63636364,
       25.36363636, 31.81818182, 39.        , 46.90909091, 55.54545455,
       64.90909091, 75.        ])

In [50]:
# Operadores de Comparación

In [52]:
numeros3 = np.linspace(10, 100, 15)

In [53]:
numeros3

array([ 10.        ,  16.42857143,  22.85714286,  29.28571429,
        35.71428571,  42.14285714,  48.57142857,  55.        ,
        61.42857143,  67.85714286,  74.28571429,  80.71428571,
        87.14285714,  93.57142857, 100.        ])

In [54]:
numeros3 >= 60

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True])

In [55]:
numeros4 = np.arange(20)

In [56]:
numeros4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
numeros4 % 5 == 0 # todos los que son divisibles entre 5

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False])

In [60]:
numeros > numeros2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [61]:
numeros == numeros2

array([False, False, False, False, False, False, False, False, False,
       False, False, False])