# Arrays con NumPy (Continuación)

## Números randomicos

In [2]:
import numpy as np

In [21]:
# Funcion 'rand' para generar numeros aleatorios entre 0 y 1

In [31]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method


In [36]:
indicadores = np.random.rand(25) # para generar un array de 1D de 25 elementos

In [7]:
indicadores

array([0.08395318, 0.24132971, 0.30386578, 0.65880892, 0.56977016,
       0.28480111, 0.92066972, 0.20360573, 0.89837453, 0.3004896 ,
       0.57006429, 0.1302397 , 0.4423628 , 0.74463626, 0.94597874,
       0.78511826, 0.1477592 , 0.16785477, 0.25419546, 0.94333318,
       0.2176223 , 0.00242965, 0.08645489, 0.94050309, 0.47343142])

In [39]:
indicadores2 = np.random.rand(5, 3) # para generar un array de 2D de 5x3

In [40]:
indicadores2

array([[0.71158231, 0.2197651 , 0.309845  ],
       [0.62826871, 0.40557859, 0.15368177],
       [0.19646872, 0.18910678, 0.6910564 ],
       [0.10746808, 0.23508769, 0.95066101],
       [0.69087314, 0.85564376, 0.06963466]])

In [32]:
# Funciones de ndarrays

In [8]:
indicadores.min()

0.002429651195902216

In [9]:
indicadores.max()

0.9459787430772268

In [10]:
indicadores.mean()

0.4527060971326071

In [12]:
indicadores.sort()

In [13]:
indicadores

array([0.00242965, 0.08395318, 0.08645489, 0.1302397 , 0.1477592 ,
       0.16785477, 0.20360573, 0.2176223 , 0.24132971, 0.25419546,
       0.28480111, 0.3004896 , 0.30386578, 0.4423628 , 0.47343142,
       0.56977016, 0.57006429, 0.65880892, 0.74463626, 0.78511826,
       0.89837453, 0.92066972, 0.94050309, 0.94333318, 0.94597874])

In [16]:
indicadores.sum()

11.317652428315176

In [18]:
indicadores.var() # Varianza

0.09726816752755635

In [20]:
indicadores.std() # Desviación estándar

0.3118784499248968

In [22]:
# Funcion 'randint' para generar numeros aleatorios enteros

In [23]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k

In [25]:
np.random.randint(1, 100, 15)

array([80, 49, 54, 91, 31, 56, 25, 48, 54, 25, 30, 20, 25, 96, 83])

In [29]:
np.random.randint(1, 100, size=(5, 4))

array([[77, 58, 81, 50],
       [35, 55, 35, 53],
       [86,  9,  2, 79],
       [90, 56, 98, 36],
       [55, 84,  7, 33]])

In [41]:
notas_alumnos = np.random.randint(1, 101, size=(15, 3))

In [42]:
notas_alumnos

array([[ 28,  17,  40],
       [100,  68,  35],
       [ 35,  52,  34],
       [ 62,  25,  66],
       [ 95,  84,  79],
       [ 67,  83,  96],
       [ 74,  64,  76],
       [ 82,  22,  72],
       [ 47,  14,  25],
       [ 72,  43,   7],
       [ 21,  30,  63],
       [100,  21,  30],
       [ 76,  73,  73],
       [ 82,  76,  66],
       [ 47,  76,  60]])

In [47]:
notas_alumnos.min(axis=0) # con axis=0 sacamos el minimo de cada columna

array([21, 14,  7])

In [49]:
notas_alumnos.min(axis=1) # con axis=0 sacamos el minimo de cada columna

array([17, 35, 34, 25, 79, 67, 64, 22, 14,  7, 21, 21, 73, 66, 47])

In [50]:
# Promedio

In [52]:
notas_alumnos.mean(axis=0) # notas promedio de todo el curso x trimestre

array([65.86666667, 49.86666667, 54.8       ])

In [53]:
notas_alumnos.mean(axis=1) # notas promedio de cada alumno en los 3 trimestres

array([28.33333333, 67.66666667, 40.33333333, 51.        , 86.        ,
       82.        , 71.33333333, 58.66666667, 28.66666667, 40.66666667,
       38.        , 50.33333333, 74.        , 74.66666667, 61.        ])

In [55]:
(28 + 17 + 40) / 3

28.333333333333332

In [56]:
# Desviacion estandar

In [57]:
notas_alumnos.std(axis=0)

array([24.54075975, 25.47382098, 23.85567717])